# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set environment variables to ensure output is logged immediately
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy all files into the container
COPY . /app

# Upgrade pip and install the package in editable mode
RUN pip install --upgrade pip \
    && pip install -e .

# Expose port based on the default configuration
EXPOSE 8000

# Command to run the MCP server
ENTRYPOINT ["mcp-duckduckgo"]
