name: Performance Testing

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'mcp_duckduckgo/**/*.py'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test,dev]"
        pip install pytest-benchmark memory-profiler

    - name: Run performance tests
      run: |
        pytest tests/test_property_based.py::TestPerformance -v --benchmark-only --benchmark-json=benchmark-results.json

    - name: Memory profiling
      run: |
        python -m memory_profiler -c "
        import mcp_duckduckgo
        from mcp_duckduckgo.search import extract_domain
        
        # Test memory usage of common operations
        for i in range(1000):
            extract_domain(f'https://example{i}.com/path')
        "

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 30

  dependency-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Update dependencies
      run: |
        pip-compile --upgrade pyproject.toml --output-file requirements-lock.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated dependency updates"
        body: |
          Automated dependency updates generated by GitHub Actions.
          
          Please review the changes and ensure all tests pass before merging.
        branch: automated/dependency-updates
        delete-branch: true